import {afterAll,beforeAll,describe,expect,it} from 'vitest';
import request from 'supertest';
import {app} from '../src/app';
import {db} from '../src/db';
import {hashPassword,signToken} from '../src/auth';
import {getAnimeSeason} from '../src/anilist';

const suffix=`${Date.now()}-lists`;let owner:any,other:any,anime:any,review:any,ownerToken:string,otherToken:string;
beforeAll(async()=>{const passwordHash=await hashPassword('password123');owner=await db.user.create({data:{email:`owner-${suffix}@test.local`,username:`owner-${suffix}`,passwordHash}});other=await db.user.create({data:{email:`other-${suffix}@test.local`,username:`other-${suffix}`,passwordHash}});anime=await db.anime.create({data:{anilistId:910000+Math.floor(Math.random()*9999),titleRomaji:'List Anime',genres:['Action']}});review=await db.review.create({data:{userId:owner.id,animeId:anime.id,rating:9,body:'Excellent'}});ownerToken=signToken(owner.id);otherToken=signToken(other.id)});
afterAll(async()=>{await db.user.deleteMany({where:{id:{in:[owner.id,other.id]}}});await db.anime.delete({where:{id:anime.id}});await db.$disconnect()});
describe('review likes and custom lists',()=>{it('likes once, rejects duplicates, and unlikes idempotently',async()=>{const first=await request(app).post(`/api/reviews/${review.id}/like`).set('authorization',`Bearer ${otherToken}`);expect(first.status).toBe(201);expect((await request(app).post(`/api/reviews/${review.id}/like`).set('authorization',`Bearer ${otherToken}`)).status).toBe(409);const profile=await request(app).get(`/api/users/${owner.username}`).set('authorization',`Bearer ${otherToken}`);expect(profile.body.user.reviews[0].likeCount).toBe(1);expect(profile.body.user.reviews[0].likedByMe).toBe(true);expect((await request(app).delete(`/api/reviews/${review.id}/like`).set('authorization',`Bearer ${otherToken}`)).status).toBe(204);expect((await request(app).delete(`/api/reviews/${review.id}/like`).set('authorization',`Bearer ${otherToken}`)).status).toBe(204)});it('enforces list ownership and manages items',async()=>{const created=await request(app).post('/api/lists').set('authorization',`Bearer ${ownerToken}`).send({name:'Favorites',isPublic:false});expect(created.status).toBe(201);const id=created.body.list.id;expect((await request(app).get(`/api/lists/${id}`).set('authorization',`Bearer ${otherToken}`)).status).toBe(404);expect((await request(app).patch(`/api/lists/${id}`).set('authorization',`Bearer ${otherToken}`).send({name:'Nope'})).status).toBe(404);const added=await request(app).post(`/api/lists/${id}/items`).set('authorization',`Bearer ${ownerToken}`).send({anilistId:anime.anilistId});expect(added.status).toBe(201);expect((await request(app).post(`/api/lists/${id}/items`).set('authorization',`Bearer ${ownerToken}`).send({anilistId:anime.anilistId})).status).toBe(409);expect((await request(app).delete(`/api/lists/${id}/items/${anime.id}`).set('authorization',`Bearer ${ownerToken}`)).status).toBe(204);expect((await request(app).delete(`/api/lists/${id}`).set('authorization',`Bearer ${ownerToken}`)).status).toBe(204)})});
describe('season calculation',()=>{it('maps all calendar seasons',()=>{expect(getAnimeSeason(new Date('2026-01-15')).season).toBe('WINTER');expect(getAnimeSeason(new Date('2026-04-01')).season).toBe('SPRING');expect(getAnimeSeason(new Date('2026-07-01')).season).toBe('SUMMER');expect(getAnimeSeason(new Date('2026-10-01')).season).toBe('FALL');expect(getAnimeSeason(new Date('2026-12-31')).season).toBe('FALL')})});
